### PR TITLE
Change pointer to default and add a better mouse hover face

### LINKED ISSUE #3: Lot of repeated errors in *Messages* buffer
```
Invalid face reference: FontAwesome
Invalid face attribute :background nil [3 times]
```
The above message keeps on repeating itself after every redisplay.

### PR DESCRIPTION
**Pull request by Compro-Prasad**
Also remove lexical-binding as it was making my tabs disappear.

Fixes #3 .

### CODE REVIEW

**Comment by ema2159** [comment]
The lexical binding is completely needed so my package is accepted in MELPA, please byte compile your centaur-tabs.el file, that should do it. On the other side I don't like the idea to change the cursor because the pointer cursor is what's used in other editors, neither to change the mouse face because it has to be generalizable on themes (not hardcoding the color) and it should be subtle and I think the underline is alright. I could offer to add a new mouse face as a defface and default it to the underline and then you could modify it as you like.

**Comment by Compro-Prasad** [comment]
I get many warnings when byte compiling the file.

<details><summary><code>*Compile-Log*</code></summary>
<p>

```
    ‘second-pattern-height-2x’
centaur-tabs.el:1543:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1544:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1544:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1545:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1546:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1547:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1547:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1548:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1548:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1549:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1549:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1550:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1550:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1551:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1551:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1552:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1552:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1555:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1555:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1556:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1556:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1557:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1557:1:Warning: Unused lexical variable
    ‘second-pattern-height’
centaur-tabs.el:1558:1:Warning: Unused lexical variable
    ‘second-pattern-height-2x’
centaur-tabs.el:1558:1:Warning: Unused lexical variable
    ‘second-pattern-height’

In centaur-tabs-monitor-window-scroll:
centaur-tabs.el:1602:42:Warning: reference to free variable
    ‘centaur-tabs-last-sticky-func-name’
centaur-tabs.el:1603:78:Warning: assignment to free variable
    ‘centaur-tabs-last-sticky-func-name’
centaur-tabs.el:1705:1:Warning: Unused lexical variable ‘selected’

In centaur-tabs-move-current-tab-to-right:
centaur-tabs.el:1755:17:Warning: assignment to free variable ‘the-buffer’
centaur-tabs.el:1757:11:Warning: reference to free variable ‘the-buffer’

In centaur-tabs-move-current-tab-to-left:
centaur-tabs.el:1777:15:Warning: assignment to free variable
    ‘not-yet-this-buf’
centaur-tabs.el:1783:19:Warning: reference to free variable ‘not-yet-this-buf’
centaur-tabs.el:1791:1:Warning: Unused lexical argument ‘buffer’

In centaur-tabs-get-extensions:
centaur-tabs.el:1894:37:Warning: reference to free variable
    ‘current-group-name’

In end of data:
centaur-tabs.el:2100:1:Warning: the function ‘helm-build-sync-source’ is not
    known to be defined.
```

</p>
</details>

**Comment by Compro-Prasad** [comment]
I don't really like the hand pointer. Would be great if we could customize it to our own preference. So, a `defcustom` should be good. Also, make the mouse-face customizable.

**Comment by ema2159** [comment]
> I get many warnings when byte compiling the file.
> `*Compile-Log*`

Yep, those are really annoying but I'm working on them so don't worry, I will give my best to make this a top package!

**Comment by ema2159** [comment]
> I don't really like the hand pointer. Would be great if we could customize it to our own preference. So, a `defcustom` should be good. Also, make the mouse-face customizable.

Yes, I'll try to add those customizations for you! When this package gets on MELPA updates and feedback will be much much easier

**Comment by ema2159** [comment]
@Compro-Prasad I added the customizations you asked for. They are:
``` elisp
(centaur-tabs-mouse-pointer) <- custom
(centaur-tabs-close-mouse-face) <- face
```
You can for example make `(centaur-tabs-close-mouse-face)` inherit the highlight so you get a strong feedback of when the mouse is hovering the close button.

**Comment by Compro-Prasad** [comment]
Works as intended. Thanks a lot.

**Pull request closed without merging**
