### PR TITLE
Generalized functions for closing and selecting a tab

### PR DESCRIPTION
**Pull request by Compro-Prasad**
Also added mouse-2 in modified-marker for closing a tab

This is my first attempt to remove some code. Make sure this doesn't break
anything in your current workflow as it doesn't add or remove any feature. It
just cleans up the code.

### CODE REVIEW

**Comment by ema2159** [comment]
This is pretty nice, I'll merge this soon

**Comment by ema2159** [comment]
Exelent job! I still have to review more carefully your other PR though.

**Comment by Compro-Prasad** [comment]
There is one thing that is still left which I added after you merged my PR.
```
(define-key map (vector 'header-line 'mouse-1) 'centaur-tabs-do-close)
```
This should be added to `centaur-tab-close-map`.

**Comment by ema2159** [comment]
Yes, that you didn't miss, I missed it when I implemented it and you carried my error. I'm changing it now! Thanks!

**Pull request merged**
