### PR TITLE
implement ace-jump style tab switching

### PR DESCRIPTION
**Pull request by Simon-Lin**
I implemented a quick tab switching function that behaves like ace-windows. It features a single entry function: `centaur-tabs-ace-jump`, which does two things when invoked:
1. shows a unique tab identifier (defaulted to 0-9, but is also user definable) on visible tabs.
2. reads an input from user and when the input matches the identifier, select to the corresponding tab.
Besides selecting tabs, the user can also change the behavior half way during stage 2 by hitting the corresponding keys (currently it is `x` for closing tab, `s` for swapping tabs, `[` and `]` to navigate tab groups), which is also user definable. 
The user can also change the default behavior by calling `centaur-tabs-ace-jump` with one  (select tabs->swap tabs) or two (select tabs->close tabs) universal arguments.

### CODE REVIEW

**Comment by ema2159** [comment]
Been wanting this feature for a while. Looks great. I will try to review it soon

**Comment by ema2159** [comment]
This is pretty good! There is a couple of things that I would like to address:
- For me, when I activate the ace-jump for the tabs and then I quit, the identifiers don't dissapear. This is most likely a bug. Luckily it may just be a missing or misplaced `(centaur-tabs-display-update)`.
- It may be a good idea to use a more noticeable face for the identifiers such as the 'highlight face, so the jump identifiers really stand out.
- It can be good to incorporate the identifiers with the other tab components, namely the close button and the modified marker. It would be good if they disappear while in jump mode.
- Lastly, and if it is not too much to ask, would it be possible to gray out the buffer while performing the jump, just like packages such as avy do?

Thanks a lot for this PR! It is a very cool feature.

**Comment by Simon-Lin** [comment]
> This is pretty good! There is a couple of things that I would like to address:
> 
>     * For me, when I activate the ace-jump for the tabs and then I quit, the identifiers don't dissapear. This is most likely a bug. Luckily it may just be a missing or misplaced `(centaur-tabs-display-update)`.
 
I cannot reproduce this bug. Can you provide more details on how you found it?

>     * It may be a good idea to use a more noticeable face for the identifiers such as the 'highlight face, so the jump identifiers really stand out.

Feature added.

>     * It can be good to incorporate the identifiers with the other tab components, namely the close button and the modified marker. It would be good if they disappear while in jump mode.

Feature added. I only hide the right close button and modified marker since the indicator is on the right of the tab. 

>     * Lastly, and if it is not too much to ask, would it be possible to gray out the buffer while performing the jump, just like packages such as avy do?
 
Feature added.

> Thanks a lot for this PR! It is a very cool feature.

**Comment by ema2159** [comment]
Hi! Regarding the bug, I cannot reproduce it either. Not sure how did I trigger it last time, guess we'll figure it out later.

Either way, outstanding job! That's some great work you've done here. Will merge it right away.
Thanks a lot! I truly appreciate it.

**Pull request merged**
