### PR TITLE
add wilmersdorf to supported theme list

### PR DESCRIPTION
**Pull request by ianpan870102**

### CODE REVIEW

**Comment by ema2159** [comment]
Nice!!! Can I see how it looks?

**Comment by ema2159** [comment]
Just one thing, shouldn't it go in the currently themed instead of the sent pull request section?

**Comment by ianpan870102** [comment]
> I checked your repo, it looks incredible!!!!

Cheers!

> shouldn't it go in the currently themed instead of the sent pull request section?

Oh yeah I misplaced it, let me quickly fix that.

**Comment by ianpan870102** [comment]
Fixed it! And here's a screenshot instead anyone else wants to have a quick look:

screenshot3

**Pull request merged**
