### PR TITLE
Use close button as modified marker like other editors

### PR DESCRIPTION
**Pull request by Compro-Prasad**
There is a spacing issue I am unable to know the source of. When the buffer is unmodified there is little space between buffer name and 'x'. But when the buffer is modified, more space is added between buffer name and modified marker. How can I fix this?

Edits
1. Its fixed
2. #1 is also fixed

### CODE REVIEW

**Comment by ema2159** [comment]
Hello! I'm glad that you're enjoying my plugin this much :D, I'll try to check this before the end of the week! That little space is added because when the buffer isn't modified the modified marker becomes " " (which takes just one character) but when it is modified it becomes " -" which is two characters long. You can change that by modifying the variable that corresponds to the marker and putting just "-". I had that idea of replacing the close button for the modified marker instead of adding it, but I wanted to implement the "on hover" functionality where the modified marker changes to the close button when the cursor is over it but I'm not quite sure if that's possible in Emacs.

**Comment by ema2159** [comment]
@Compro-Prasad excellent job, thanks for the help man! By the way, I already submitted a PR in MELPA so this package gets uploaded, let's hope they accept it soon. Thanks for contributing and submitting the first PR in my repo, this is my first time authoring a package so let's hope I do it well!

**Comment by Compro-Prasad** [comment]
I am enjoying this plugin but there are some issues which I don't understand properly. Like:
1. `centaur-tabs-forward` and `centaur-tabs-backward` switch groups
2. No way to actually switch between groups. In `tabbar-ruler` there is a **+** in the top left corner to switch between groups.
3. There is no visual feedback when mouse hovers over close button. I think this can be fixed by adding `mouse-face` which will just change the opacity. Don't know if it will work but `mouse-face` is what we are left with.

Also, best of luck with your first package on MELPA.

I was also researching to make a good tabs plugin. First I came to know about `tabbar-ruler` which has better functionality than this package but it got too slow when I tried to change some stuff. Problem with `tabbar` like plugins is that they use the header line which can also be used by any other mode.

Then I came across https://github.com/conao3/navbar.el which provides a small window for the current frame at the top which can be used to show many things. It is more like a library to make other plugins. `centaur-tabs` could use `navbar.el` to show all the tabs so that other modes can freely use the header line for their own purposes.

**Comment by ema2159** [comment]
> 1. centaur-tabs-forward and centaur-tabs-backward switch groups

I think this only happens when the buffer groups are not defined so the plugin assings a buffer group to each tab.

> 2. No way to actually switch between groups. In tabbar-ruler there is a + in the top left corner to switch between groups.

I use the Ivy functionality to switch groups (there's also a Helm functionality implemented by the awesome-tab author that I haven't tried yet because I don't use Helm).
I could add the feature you mention in a future, but remember, I intended this plugin to be keyboard oriented so there's some features that I'll give a higher priority. Don't be afraid to submit a PR with the functionality though, only remember to document the hell out of it jaja. I'll implement a CI checking for pull requests in a near future to ensure that. 

> 3.  There is no visual feedback when mouse hovers over close button. I think this can be fixed by adding mouse-face which will just change the opacity. Don't know if it will work but mouse-face is what we are left with.

That's easy to implement, but what I really want to implement is for the modified marker to disappear when the mouse is over it and display the close button instead, but I'm not quite sure how.

I also came from tabbar-ruler (that was my original forking candidate, but the code was goddamn chaotic). It had to many functionalities that I didn't particularly liked so I decided to create this.

The navbar idea sounds nice but I'll have to study it first

**Pull request merged**
