### PR TITLE
Simplified code in centaur-tabs-line-tab. It might be more efficient

### PR DESCRIPTION
**Pull request by Compro-Prasad**

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
This should change any behaviour apart from the `help-echo`. I moved `not-read-only-p` to the definition of `modified-p` as it was always used in conjunction with `modified-p`. So, now using `modified-p` is same as using `(and modified-p not-read-only-p)`.

**Comment by ema2159** [comment]
Ok now I see, this seems like a nice PR, could you just remove those added help echoes?

**Comment by Compro-Prasad** [comment]
I am actually busy these days. It would be great if you could wait or change the code after merging.

**Comment by ema2159** [comment]
Yep, I got you!

**Comment by ema2159** [comment]
Thanks man, you keep making great improvements to `centaur-tabs`, you're awesome!

**Pull request merged**
