### PR TITLE
add options centaur-tabs-adjust-buffer-order

### PR DESCRIPTION
**Pull request by jixiuf**
#17

### CODE REVIEW

**Comment by ema2159** [comment]
Wow! This one is big! I'll need some time to review it properly but it looks good! Thanks man!

**Comment by ema2159** [comment]
3 things:
- Change `first` function to `cl-first`
- Change `copy-list` function to `cl-copy-list`
This in order to use `cl-lib` instead of the deprecated `cl`

- Fix `centaur-tabs-adjust-buffer-order` custom documentation. 
The first line of the docstring must end in "."

**Comment by ema2159** [comment]
Does this work for you? I'm not getting it to work for some reason. I'm setting in my config `(setq centaur-tabs-adjust-buffer-order 'right) but it simply doesn't seem to do anything`

**Comment by ema2159** [comment]
Meanwhile I'll implement @manateelazycat's fix. Another thing, you must provide a custom option where no buffer reordering is implemented at all!

**Comment by jixiuf** [comment]
English is not my first language ,so could you help fix the documentation problem

**Comment by ema2159** [comment]
Neither is mine jaja! I'll help you with that though

**Comment by ema2159** [comment]
Good, it seems to work right now

**Comment by user-b** [comment]
Hello, and thanks for centaur-tabs, not a fan of using tabs in general but this project (with the automatic hidding hack) is pretty good.

But `centaur-tabs-adjust-buffer-order` is not working here. Neither with ivy or ido. Any idea whay should I try?

Thanks.

**Pull request merged**
