### PR TITLE
Add: natural tab close behavior like modern editor

### PR DESCRIPTION
**Pull request by black7375**
output-2020-11-18-13:41:31

I made it by referring to the [Making Emacs tabs work like in Atom](https://andreyorst.gitlab.io/posts/2020-05-07-making-emacs-tabs-work-like-in-atom/).

Expected behavior
> - Buffer can exist without a tab, but tab can not exist without a buffer,
> - If tab was closed buffer should be killed only if there are no tabs for this buffer left,
> - If tab was closed and there are no more tabs in the window, window should be killed.

### CODE REVIEW

**Comment by ema2159** [comment]
Hey! This seems interesting. Could you elaborate a little bit more on this idea?

**Comment by black7375** [comment]
Currently, even if there are several windows(splited pane), press the exit button to turn it off all at once.
Simply put, it kill the buffer!!

output-2020-11-19-01:15:52
- Two `New Empty<2> ` windows are on. At this point, press the `close` and they're all off.

When using a split window,
- Buffer has multiple windows: `close` the splited window.
- Buffer has only one window or in the background: `close` buffer
output-2020-11-19-01:27:39

I think that it is more natural .
Because it doesn't affect what you're doing in other windows.

**Comment by ema2159** [comment]
Sounds very useful! I am going to test it out! It will be a very useful feature.

**Comment by black7375** [comment]
Have you tested it?

If you haven't tried it yet,
You can easily experience by turn on `M-x ielm` and pasting the code above.

**Comment by ema2159** [comment]
Yes! I have. Sorry, I've been a little bit busy. I tested it a week ago or so and I thought there were some inconsistencies with the behavior but that's not the case, I just misinterpreted it. So, for the buffer to remain open when it's "closed" in one of the windows, it has to be selected in another window right? Everything seems fine and I'm ok with merging this if that's the case!

**Comment by black7375** [comment]
After switching windows,
If the target tab is Background, subtract `1` from the `window count`.
(Before that, the window was closed because the number of background tabs was included.)

It's definitely better.
That was a good point.

**Comment by ema2159** [comment]
Sorry for the extremely long delay! Merging this right now. Awesome job man!

**Comment by tralph3** [comment]
Sorry if I'm necro-bumping this, but is there a function in Centaur Tabs to trigger this behavior? I'd like to use a key binding to close my buffers, and I want this behavior to be there. If I simply kill the buffer with emacs, it doesn't do it.

Is there a function that lets me kill the current buffer within Centaur Tabs?

**Pull request merged**
