### PR TITLE
Create .dir-locals.el to set indent variables in emacs-lisp-mode

### PR DESCRIPTION
**Pull request by Compro-Prasad**

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
Is there something missing in here?

**Comment by ema2159** [comment]
Nope, I just finished my internship yesterday so I had to hand my work computer which is the one that I used to work in this. I have my personal computer but it just have Windows so I'll have to install a Virtual Machine or something

**Comment by Compro-Prasad** [comment]
My bad. The value for `indent-tabs-mode` is now `t`.

**Comment by ema2159** [comment]
I've managed to find a computer to work for now, I'll merge these two PRs

**Pull request merged**
